services:
  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: trading_simulator_db_username
      POSTGRES_PASSWORD: trading_simulator_db_password
      POSTGRES_DB: trading_simulator_db
    command: >
      -c shared_preload_libraries=timescaledb
      -c max_connections=100
      -c timezone=UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trading_simulator_db_username -d trading_simulator_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: